graph TD
    junit:junit:4.12
    junit:junit:4.12 --> org.hamcrest:hamcrest-core:1.3
    junit:junit:4.12 --> com.github.stephenc.wagon:wagon-gitsite:0.4.1
    junit:junit:4.12 --> org.apache.maven.doxia:doxia-module-markdown:1.5
    junit:junit:4.12 --> org.apache.maven.surefire:surefire-junit47:2.17
    junit:junit:4.12 --> org.apache.maven.wagon:wagon-provider-api:1.0
    junit:junit:4.12 --> org.apache.maven.wagon:wagon-provider-test:1.0
    junit:junit:4.12 --> org.apache.maven.wagon:wagon-ssh-common-test:1.0
    junit:junit:4.12 --> org.apache.maven.wagon:wagon-ssh-common:1.0
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> org.codehaus.plexus:plexus-interactivity-api:1.0-alpha-6
    junit:junit:4.12 --> org.codehaus.plexus:plexus-container-default:1.5.5
    junit:junit:4.12 --> org.codehaus.plexus:plexus-utils:3.0
    junit:junit:4.12 --> org.apache.maven.scm:maven-scm-api:1.5
    junit:junit:4.12 --> org.apache.maven.scm:maven-scm-manager-plexus:1.5
    junit:junit:4.12 --> org.apache.maven.scm:maven-scm-test:1.5
    junit:junit:4.12 --> org.apache.maven.scm:maven-scm-provider-gitexe:1.5
    junit:junit:4.12 --> org.apache.maven.scm:maven-scm-provider-git-commons:1.5
    junit:junit:4.12 --> org.apache.maven.wagon:wagon-provider-api:1.0
    junit:junit:4.12 --> org.apache.maven.wagon:wagon-provider-test:1.0
    junit:junit:4.12 --> junit:junit:unknown
    junit:junit:4.12 --> com.github.stephenc.wagon:wagon-gitsite:${project.version}
    junit:junit:4.12 --> net.sf.docbook:docbook-xml:5.0-all
    junit:junit:4.12 --> org.codehaus.plexus:plexus-utils:unknown
    junit:junit:4.12 --> easymock:easymock:1.2_Java1.3
    junit:junit:4.12 --> junit:junit:unknown
    junit:junit:4.12 --> org.apache.maven.wagon:wagon-provider-api:unknown
    junit:junit:4.12 --> org.codehaus.plexus:plexus-container-default:unknown
    junit:junit:4.12 --> easymock:easymock:1.2_Java1.3
    junit:junit:4.12 --> org.mortbay.jetty:jetty:6.1.11
    junit:junit:4.12 --> junit:junit:unknown
    junit:junit:4.12 --> org.mortbay.jetty:jetty-util:${project.version}
    junit:junit:4.12 --> org.mortbay.jetty:servlet-api-2.5:${project.version}
    junit:junit:4.12 --> org.codehaus.plexus:plexus-container-default:unknown
    junit:junit:4.12 --> org.codehaus.plexus:plexus-utils:unknown
    junit:junit:4.12 --> org.apache.maven.wagon:wagon-ssh-common:unknown
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> org.codehaus.plexus:plexus-utils:unknown
    junit:junit:4.12 --> org.codehaus.plexus:plexus-interactivity-api:unknown
    junit:junit:4.12 --> org.codehaus.plexus:plexus-utils:1.4
    junit:junit:4.12 --> org.codehaus.plexus:plexus-utils:unknown
    junit:junit:4.12 --> org.codehaus.plexus:plexus-classworlds:unknown
    junit:junit:4.12 --> org.apache.xbean:xbean-reflect:unknown
    junit:junit:4.12 --> com.google.collections:google-collections:unknown
    junit:junit:4.12 --> junit:junit:unknown
    junit:junit:4.12 --> junit:junit:3.8.2
    junit:junit:4.12 --> junit:junit:unknown
    junit:junit:4.12 --> org.codehaus.plexus:plexus-container-default:unknown
    junit:junit:4.12 --> org.apache.maven.scm:maven-scm-api:unknown
    junit:junit:4.12 --> org.apache.maven.scm:maven-scm-api:unknown
    junit:junit:4.12 --> org.apache.maven.scm:maven-scm-manager-plexus:unknown
    junit:junit:4.12 --> regexp:regexp:unknown
    junit:junit:4.12 --> org.apache.maven.scm:maven-scm-provider-git-commons:unknown
    junit:junit:4.12 --> org.apache.maven.scm:maven-scm-provider-gittest:unknown
    junit:junit:4.12 --> regexp:regexp:unknown
    junit:junit:4.12 --> org.pegdown:pegdown:1.2.1
    junit:junit:4.12 --> org.apache.maven.doxia:doxia-module-xhtml:unknown
    junit:junit:4.12 --> org.codehaus.plexus:plexus-utils:unknown
    junit:junit:4.12 --> org.parboiled:parboiled-java:1.1.4
    junit:junit:4.12 --> net.sf.jtidy:jtidy:r938
    junit:junit:4.12 --> org.specs2:specs2_2.9.2:1.12.2
    junit:junit:4.12 --> org.parboiled:parboiled-core:1.1.4
    junit:junit:4.12 --> org.testng:testng:5.14.1
    junit:junit:4.12 --> org.scalatest:scalatest_2.10.0-RC3:1.8-B1
    junit:junit:4.12 --> org.ow2.asm:asm:4.1
    junit:junit:4.12 --> org.ow2.asm:asm-tree:4.1
    junit:junit:4.12 --> org.ow2.asm:asm-analysis:4.1
    junit:junit:4.12 --> org.ow2.asm:asm-util:4.1
    junit:junit:4.12 --> org.testng:testng:5.14.1
    junit:junit:4.12 --> org.scalatest:scalatest_2.10.0-RC3:1.8-B1
    junit:junit:4.12 --> ant:ant:1.6.5
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> org.beanshell:bsh:2.0b4
    junit:junit:4.12 --> com.google.inject:guice:2.0
    junit:junit:4.12 --> com.beust:jcommander:1.5
    junit:junit:4.12 --> ant:ant:1.6.5
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> org.beanshell:bsh:2.0b4
    junit:junit:4.12 --> com.google.inject:guice:2.0
    junit:junit:4.12 --> com.beust:jcommander:1.7
    junit:junit:4.12 --> xerces:xercesImpl:2.6.2
    junit:junit:4.12 --> xml-apis:xml-apis:1.3.04
    junit:junit:4.12 --> aopalliance:aopalliance:unknown
    junit:junit:4.12 --> org.testng:testng:5.12.1
    junit:junit:4.12 --> ant:ant:1.6.5
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> org.beanshell:bsh:2.0b4
    junit:junit:4.12 --> com.google.inject:guice:2.0
    junit:junit:4.12 --> org.testng:testng:5.12.1
    junit:junit:4.12 --> org.scala-lang:scala-library:2.10.0-RC3
    junit:junit:4.12 --> org.scala-lang:scala-compiler:2.10.0-RC3
    junit:junit:4.12 --> org.scala-lang:scala-actors:2.10.0-RC3
    junit:junit:4.12 --> org.scala-lang:scala-reflect:2.10.0-RC3
    junit:junit:4.12 --> org.scala-tools.testing:test-interface:0.5
    junit:junit:4.12 --> org.antlr:stringtemplate:3.2
    junit:junit:4.12 --> org.scalacheck:scalacheck_2.10.0-RC3:1.10.0
    junit:junit:4.12 --> org.easymock:easymockclassextension:3.1
    junit:junit:4.12 --> org.jmock:jmock-legacy:2.5.1
    junit:junit:4.12 --> org.mockito:mockito-all:1.9.0
    junit:junit:4.12 --> org.testng:testng:6.3.1
    junit:junit:4.12 --> com.google.inject:guice:3.0
    junit:junit:4.12 --> junit:junit:4.10
    junit:junit:4.12 --> net.sourceforge.cobertura:cobertura:1.9.1
    junit:junit:4.12 --> org.apache.commons:commons-io:1.3.2
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> antlr:antlr:2.7.7
    junit:junit:4.12 --> org.scala-lang:scala-library:2.10.0-RC3
    junit:junit:4.12 --> org.scala-tools.testing:test-interface:0.5
    junit:junit:4.12 --> org.scala-lang:scala-actors:2.10.0-RC3
    junit:junit:4.12 --> org.easymock:easymock:${project.version}
    junit:junit:4.12 --> ${pom.groupId}:jmock:${pom.version}
    junit:junit:4.12 --> org.objenesis:objenesis:1.0
    junit:junit:4.12 --> cglib:cglib-nodep:2.1_3
    junit:junit:4.12 --> ant:ant:1.6.5
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> org.beanshell:bsh:2.0b4
    junit:junit:4.12 --> com.google.inject:guice:2.0
    junit:junit:4.12 --> com.beust:jcommander:1.5
    junit:junit:4.12 --> ant:ant:1.6.5
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> org.beanshell:bsh:2.0b4
    junit:junit:4.12 --> com.google.inject:guice:2.0
    junit:junit:4.12 --> com.beust:jcommander:1.12
    junit:junit:4.12 --> org.yaml:snakeyaml:1.6
    junit:junit:4.12 --> org.testng:testng:5.14.2
    junit:junit:4.12 --> ant:ant:1.6.5
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> org.beanshell:bsh:2.0b4
    junit:junit:4.12 --> com.google.inject:guice:2.0
    junit:junit:4.12 --> com.beust:jcommander:1.5
    junit:junit:4.12 --> ant:ant:1.6.5
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> org.beanshell:bsh:2.0b4
    junit:junit:4.12 --> com.google.inject:guice:2.0
    junit:junit:4.12 --> com.beust:jcommander:1.10
    junit:junit:4.12 --> org.testng:testng:5.14.1
    junit:junit:4.12 --> junit:junit:3.8.2
    junit:junit:4.12 --> org.springframework:spring:2.5.6
    junit:junit:4.12 --> org.apache.velocity:velocity:1.6.2
    junit:junit:4.12 --> aopalliance:aopalliance:1.0
    junit:junit:4.12 --> asm:asm:2.2.3
    junit:junit:4.12 --> asm:asm-commons:2.2.3
    junit:junit:4.12 --> asm:asm-util:2.2.3
    junit:junit:4.12 --> org.aspectj:aspectjrt:1.6.1
    junit:junit:4.12 --> org.aspectj:aspectjweaver:1.6.1
    junit:junit:4.12 --> backport-util-concurrent:backport-util-concurrent:3.0
    junit:junit:4.12 --> c3p0:c3p0:0.9.1.2
    junit:junit:4.12 --> cglib:cglib-nodep:2.1_3
    junit:junit:4.12 --> commons-attributes:commons-attributes-api:2.2
    junit:junit:4.12 --> commons-attributes:commons-attributes-compiler:2.2
    junit:junit:4.12 --> commons-beanutils:commons-beanutils:1.7.0
    junit:junit:4.12 --> commons-collections:commons-collections:3.2
    junit:junit:4.12 --> commons-dbcp:commons-dbcp:1.2.2
    junit:junit:4.12 --> commons-fileupload:commons-fileupload:1.2
    junit:junit:4.12 --> commons-httpclient:commons-httpclient:3.1
    junit:junit:4.12 --> commons-logging:commons-logging:1.1.1
    junit:junit:4.12 --> commons-pool:commons-pool:1.3
    junit:junit:4.12 --> com.bea.wlplatform:commonj-twm:1.1
    junit:junit:4.12 --> com.experlog:xapool:1.5.0
    junit:junit:4.12 --> org.apache.ibatis:ibatis-sqlmap:2.3.4.726
    junit:junit:4.12 --> com.jamonapi:jamon:2.4
    junit:junit:4.12 --> com.lowagie:itext:2.0.7
    junit:junit:4.12 --> com.oracle.toplink:toplink:10.1.3
    junit:junit:4.12 --> com.oracle:toplink-essentials:2.41
    junit:junit:4.12 --> com.oracle:oc4j:1.0
    junit:junit:4.12 --> org.freemarker:freemarker:2.3.14
    junit:junit:4.12 --> org.codehaus.groovy:groovy:1.5.6
    junit:junit:4.12 --> com.caucho:hessian:3.1.3
    junit:junit:4.12 --> jasperreports:jasperreports:2.0.5
    junit:junit:4.12 --> javax.activation:activation:1.1
    junit:junit:4.12 --> javax.ejb:ejb:3.0
    junit:junit:4.12 --> javax.faces:jsf-api:1.1
    junit:junit:4.12 --> javax.jdo:jdo2-api:2.0
    junit:junit:4.12 --> javax.jms:jms:1.1
    junit:junit:4.12 --> javax.mail:mail:1.4
    junit:junit:4.12 --> javax.persistence:persistence-api:1.0
    junit:junit:4.12 --> javax.portlet:portlet-api:1.0
    junit:junit:4.12 --> javax.resource:connector-api:1.5
    junit:junit:4.12 --> javax.servlet:jsp-api:2.0
    junit:junit:4.12 --> javax.servlet:jstl:1.1.0
    junit:junit:4.12 --> javax.servlet:servlet-api:2.4
    junit:junit:4.12 --> javax.transaction:jta:1.1
    junit:junit:4.12 --> javax.xml:jaxrpc-api:1.1
    junit:junit:4.12 --> jexcelapi:jxl:2.6.6
    junit:junit:4.12 --> jotm:jotm:2.0.10
    junit:junit:4.12 --> org.jruby:jruby:1.0.1
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> log4j:log4j:1.2.15
    junit:junit:4.12 --> net.sf.ehcache:ehcache:1.5.0
    junit:junit:4.12 --> org.apache.axis:axis:1.4
    junit:junit:4.12 --> org.apache.tiles:tiles-api:2.0.6
    junit:junit:4.12 --> org.apache.tiles:tiles-core:2.0.6
    junit:junit:4.12 --> org.apache.tiles:tiles-jsp:2.0.6
    junit:junit:4.12 --> org.beanshell:bsh:2.0b4
    junit:junit:4.12 --> org.hibernate:hibernate:3.2.6.ga
    junit:junit:4.12 --> org.hibernate:hibernate-entitymanager:3.3.2.GA
    junit:junit:4.12 --> org.apache.poi:poi:3.0.1-FINAL
    junit:junit:4.12 --> opensymphony:quartz-all:1.6.0
    junit:junit:4.12 --> struts:struts:1.2.9
    junit:junit:4.12 --> taglibs:standard:1.1.2
    junit:junit:4.12 --> tomcat:catalina:5.5.23
    junit:junit:4.12 --> velocity:velocity:1.5
    junit:junit:4.12 --> velocity-tools:velocity-tools-generic:1.4
    junit:junit:4.12 --> velocity-tools:velocity-tools-view:1.4
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> log4j:log4j:1.2.12
    junit:junit:4.12 --> logkit:logkit:1.0.1
    junit:junit:4.12 --> avalon-framework:avalon-framework:4.1.3
    junit:junit:4.12 --> javax.servlet:servlet-api:2.3
    junit:junit:4.12 --> bouncycastle:bcmail-jdk14:138
    junit:junit:4.12 --> bouncycastle:bcprov-jdk14:138
    junit:junit:4.12 --> antlr:antlr:2.7.6
    junit:junit:4.12 --> asm:asm:2.2
    junit:junit:4.12 --> junit:junit:3.8.2
    junit:junit:4.12 --> commons-cli:commons-cli:1.0
    junit:junit:4.12 --> org.apache.ant:ant:1.7.0
    junit:junit:4.12 --> org.apache.ant:ant-junit:1.7.0
    junit:junit:4.12 --> org.apache.ant:ant-launcher:1.7.0
    junit:junit:4.12 --> jmock:jmock:1.2.0
    junit:junit:4.12 --> jmock:jmock-cglib:1.2.0
    junit:junit:4.12 --> cglib:cglib-nodep:2.1_3
    junit:junit:4.12 --> asm:asm-util:2.2
    junit:junit:4.12 --> asm:asm-attrs:2.2
    junit:junit:4.12 --> asm:asm-analysis:2.2
    junit:junit:4.12 --> asm:asm-tree:2.2
    junit:junit:4.12 --> bsf:bsf:2.4.0
    junit:junit:4.12 --> commons-logging:commons-logging:1.1
    junit:junit:4.12 --> mx4j:mx4j:3.0.2
    junit:junit:4.12 --> mockobjects:mockobjects-core:0.09
    junit:junit:4.12 --> xmlunit:xmlunit:1.1
    junit:junit:4.12 --> hsqldb:hsqldb:1.8.0.7
    junit:junit:4.12 --> javax.servlet:servlet-api:2.4
    junit:junit:4.12 --> javax.servlet:jsp-api:2.0
    junit:junit:4.12 --> com.thoughtworks.xstream:xstream:1.2.2
    junit:junit:4.12 --> jline:jline:0.9.94
    junit:junit:4.12 --> org.apache.ant:ant-launcher:1.7.0
    junit:junit:4.12 --> xerces:xercesImpl:2.8.1
    junit:junit:4.12 --> xml-apis:xml-apis:1.3.03
    junit:junit:4.12 --> org.apache.ant:ant:1.7.0
    junit:junit:4.12 --> junit:junit:3.8.2
    junit:junit:4.12 --> commons-logging:commons-logging:1.0.4
    junit:junit:4.12 --> junit:junit:3.8.2
    junit:junit:4.12 --> dom4j:dom4j:unknown
    junit:junit:4.12 --> jdom:jdom:unknown
    junit:junit:4.12 --> joda-time:joda-time:unknown
    junit:junit:4.12 --> com.megginson.sax:xml-writer:unknown
    junit:junit:4.12 --> stax:stax:unknown
    junit:junit:4.12 --> org.codehaus.woodstox:wstx-asl:unknown
    junit:junit:4.12 --> stax:stax-api:unknown
    junit:junit:4.12 --> xom:xom:unknown
    junit:junit:4.12 --> xpp3:xpp3_min:unknown
    junit:junit:4.12 --> cglib:cglib-nodep:unknown
    junit:junit:4.12 --> org.codehaus.jettison:jettison:unknown
    junit:junit:4.12 --> junit:junit:unknown
    junit:junit:4.12 --> jmock:jmock:unknown
    junit:junit:4.12 --> oro:oro:unknown
    junit:junit:4.12 --> commons-lang:commons-lang:unknown
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> commons-beanutils:commons-beanutils:1.7.0
    junit:junit:4.12 --> commons-collections:commons-collections:[2.1,)
    junit:junit:4.12 --> commons-digester:commons-digester:[1.7,)
    junit:junit:4.12 --> commons-logging:commons-logging:[1.0,)
    junit:junit:4.12 --> org.hibernate:hibernate:[3.0.1,)
    junit:junit:4.12 --> com.lowagie:itext:[1.02b,)
    junit:junit:4.12 --> jfree:jcommon:[1.0.0,)
    junit:junit:4.12 --> jfree:jfreechart:[1.0.0,)
    junit:junit:4.12 --> org.apache.poi:poi:3.0.1-FINAL
    junit:junit:4.12 --> javax.servlet:servlet-api:2.2
    junit:junit:4.12 --> xalan:xalan:[2.6.0,)
    junit:junit:4.12 --> xml-apis:xml-apis:1.3.02
    junit:junit:4.12 --> eclipse:jdtcore:[3.1.0,)
    junit:junit:4.12 --> groovy:groovy-all-minimal:1.0
    junit:junit:4.12 --> ant:ant:[1.5.1,)
    junit:junit:4.12 --> net.sourceforge.jexcelapi:jxl:2.6
    junit:junit:4.12 --> com.keypoint:png-encoder:1.5
    junit:junit:4.12 --> commons-javaflow:commons-javaflow:20060411
    junit:junit:4.12 --> mondrian:mondrian:2.3.2.8944
    junit:junit:4.12 --> javax.persistence:persistence-api:1.0
    junit:junit:4.12 --> antlr:antlr:2.7.5
    junit:junit:4.12 --> javax.xml.soap:saaj-api:1.3
    junit:junit:4.12 --> jaxen:jaxen:1.1.1
    junit:junit:4.12 --> org.beanshell:bsh:2.0b4
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-bridge:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-gvt:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-util:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-svg-dom:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-dom:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-script:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-css:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-svggen:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-awt-util:1.7
    junit:junit:4.12 --> commons-logging:commons-logging:1.1
    junit:junit:4.12 --> log4j:log4j:1.2.13
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-anim:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-awt-util:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-css:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-dom:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-ext:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-gvt:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-parser:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-script:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-svg-dom:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-util:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-xml:1.7
    junit:junit:4.12 --> xalan:xalan:2.6.0
    junit:junit:4.12 --> xml-apis:xml-apis:1.3.04
    junit:junit:4.12 --> xml-apis:xml-apis-ext:1.3.04
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-awt-util:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-dom:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-ext:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-parser:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-svg-dom:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-util:1.7
    junit:junit:4.12 --> xml-apis:xml-apis:1.3.04
    junit:junit:4.12 --> xml-apis:xml-apis-ext:1.3.04
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-util:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-css:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-ext:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-util:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-xml:1.7
    junit:junit:4.12 --> xalan:xalan:2.6.0
    junit:junit:4.12 --> xml-apis:xml-apis:1.3.04
    junit:junit:4.12 --> xml-apis:xml-apis-ext:1.3.04
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-ext:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-util:1.7
    junit:junit:4.12 --> xml-apis:xml-apis:1.3.04
    junit:junit:4.12 --> xml-apis:xml-apis-ext:1.3.04
    junit:junit:4.12 --> xml-apis:xml-apis:1.3.04
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-util:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-awt-util:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-util:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-xml:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-anim:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-awt-util:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-css:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-dom:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-ext:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-parser:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-util:1.7
    junit:junit:4.12 --> xml-apis:xml-apis:1.3.04
    junit:junit:4.12 --> xml-apis:xml-apis-ext:1.3.04
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-awt-util:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-bridge:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-util:1.7
    junit:junit:4.12 --> xml-apis:xml-apis:1.3.04
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-bridge:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-dom:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-ext:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-svg-dom:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-util:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-js:1.7
    junit:junit:4.12 --> xml-apis:xml-apis:1.3.04
    junit:junit:4.12 --> xml-apis:xml-apis:1.3.04
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-awt-util:1.7
    junit:junit:4.12 --> org.apache.xmlgraphics:batik-util:1.7
    junit:junit:4.12 --> xml-apis:xml-apis:1.3.04
    junit:junit:4.12 --> backport-util-concurrent:backport-util-concurrent:3.0
    junit:junit:4.12 --> jline:jline:0.9.91
    junit:junit:4.12 --> asm:asm:2.2.3
    junit:junit:4.12 --> asm:asm-commons:2.2.3
    junit:junit:4.12 --> ant:ant-junit:1.6.5
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> ant:ant-nodeps:1.6.5
    junit:junit:4.12 --> ant-contrib:ant-contrib:1.0b2
    junit:junit:4.12 --> ant:ant-junit:1.6.5
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> sun.jdk:tools:1.4.2
    junit:junit:4.12 --> javax.mail:mail:1.4
    junit:junit:4.12 --> javax.jms:jms:1.1
    junit:junit:4.12 --> com.sun.jdmk:jmxtools:1.2.1
    junit:junit:4.12 --> com.sun.jmx:jmxri:1.2.1
    junit:junit:4.12 --> oro:oro:2.0.8
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> backport-util-concurrent:backport-util-concurrent:unknown
    junit:junit:4.12 --> commons-logging:commons-logging:unknown
    junit:junit:4.12 --> commons-collections:commons-collections:unknown
    junit:junit:4.12 --> net.sf.jsr107cache:jsr107cache:unknown
    junit:junit:4.12 --> dom4j:dom4j:unknown
    junit:junit:4.12 --> org.hibernate:hibernate:unknown
    junit:junit:4.12 --> net.sf.hibernate:hibernate:unknown
    junit:junit:4.12 --> javax.servlet:servlet-api:unknown
    junit:junit:4.12 --> junit:junit:unknown
    junit:junit:4.12 --> httpunit:httpunit:unknown
    junit:junit:4.12 --> commons-httpclient:commons-httpclient:unknown
    junit:junit:4.12 --> checkstyle:checkstyle:unknown
    junit:junit:4.12 --> checkstyle:checkstyle-optional:unknown
    junit:junit:4.12 --> com.cenqua.clover:clover:unknown
    junit:junit:4.12 --> org.springframework:spring:unknown
    junit:junit:4.12 --> org.springframework:spring-aop:unknown
    junit:junit:4.12 --> org.springframework:spring-aspects:unknown
    junit:junit:4.12 --> org.springframework:spring-mock:unknown
    junit:junit:4.12 --> org.acegisecurity:acegi-security:unknown
    junit:junit:4.12 --> jgroups:jgroups-all:2.4.1
    junit:junit:4.12 --> javax.servlet:servlet-api:2.4
    junit:junit:4.12 --> commons-logging:commons-logging-api:1.1
    junit:junit:4.12 --> junit:junit:4.0
    junit:junit:4.12 --> org.easymock:easymock:2.2
    junit:junit:4.12 --> org.apache.tiles:tiles-api:${pom.version}
    junit:junit:4.12 --> commons-digester:commons-digester:1.8
    junit:junit:4.12 --> commons-logging:commons-logging-api:1.1
    junit:junit:4.12 --> javax.servlet:servlet-api:2.4
    junit:junit:4.12 --> javax.portlet:portlet-api:1.0
    junit:junit:4.12 --> junit:junit:4.0
    junit:junit:4.12 --> org.easymock:easymock:2.2
    junit:junit:4.12 --> org.apache.shale:shale-test:1.0.4
    junit:junit:4.12 --> org.apache.tiles:tiles-core:${pom.version}
    junit:junit:4.12 --> commons-digester:commons-digester:1.8
    junit:junit:4.12 --> commons-logging:commons-logging-api:1.1
    junit:junit:4.12 --> javax.servlet:servlet-api:2.4
    junit:junit:4.12 --> javax.servlet:jsp-api:2.0
    junit:junit:4.12 --> junit:junit:4.0
    junit:junit:4.12 --> org.easymock:easymock:2.2
    junit:junit:4.12 --> org.apache.shale:shale-test:1.0.4
    junit:junit:4.12 --> net.sf.ehcache:ehcache:1.2.3
    junit:junit:4.12 --> swarmcache:swarmcache:1.0RC2
    junit:junit:4.12 --> jboss:jboss-cache:1.2.2
    junit:junit:4.12 --> jgroups:jgroups-all:2.2.8
    junit:junit:4.12 --> javax.transaction:jta:1.0.1B
    junit:junit:4.12 --> commons-logging:commons-logging:1.0.4
    junit:junit:4.12 --> c3p0:c3p0:0.9.1
    junit:junit:4.12 --> asm:asm-attrs:1.5.3
    junit:junit:4.12 --> javax.security:jacc:1.0
    junit:junit:4.12 --> dom4j:dom4j:1.6.1
    junit:junit:4.12 --> antlr:antlr:2.7.6
    junit:junit:4.12 --> cglib:cglib:2.1_3
    junit:junit:4.12 --> opensymphony:oscache:2.1
    junit:junit:4.12 --> asm:asm:1.5.3
    junit:junit:4.12 --> commons-collections:commons-collections:2.1.1
    junit:junit:4.12 --> ant:ant:1.6.5
    junit:junit:4.12 --> proxool:proxool:0.8.3
    junit:junit:4.12 --> commons-logging:commons-logging:1.0.4
    junit:junit:4.12 --> commons-collections:commons-collections:2.1
    junit:junit:4.12 --> org.hibernate:hibernate:3.2.0.cr3
    junit:junit:4.12 --> net.sf.hibernate:hibernate:2.1.8
    junit:junit:4.12 --> javax.servlet:servlet-api:2.4
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> httpunit:httpunit:1.6
    junit:junit:4.12 --> commons-httpclient:commons-httpclient:3.0.1
    junit:junit:4.12 --> commons-logging:commons-logging:1.0.4
    junit:junit:4.12 --> ant:ant:1.6.5
    junit:junit:4.12 --> c3p0:c3p0:0.9.0
    junit:junit:4.12 --> proxool:proxool:0.8.3
    junit:junit:4.12 --> ehcache:ehcache:1.2
    junit:junit:4.12 --> opensymphony:oscache:2.1
    junit:junit:4.12 --> swarmcache:swarmcache:1.0RC2
    junit:junit:4.12 --> jboss:jboss-cache:1.2.2
    junit:junit:4.12 --> jgroups:jgroups-all:2.2.8
    junit:junit:4.12 --> cglib:cglib:2.1_3
    junit:junit:4.12 --> asm:asm:1.5.3
    junit:junit:4.12 --> asm:asm-attrs:1.5.3
    junit:junit:4.12 --> commons-collections:commons-collections:2.1.1
    junit:junit:4.12 --> javax.security:jacc:1.0
    junit:junit:4.12 --> dom4j:dom4j:1.6.1
    junit:junit:4.12 --> javax.transaction:jta:1.0.1B
    junit:junit:4.12 --> antlr:antlr:2.7.6
    junit:junit:4.12 --> xerces:xmlParserAPIs:2.2.1
    junit:junit:4.12 --> xerces:xercesImpl:2.6.2
    junit:junit:4.12 --> nekohtml:nekohtml:0.9.1
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> rhino:js:1.5R4.1
    junit:junit:4.12 --> javax.servlet:servlet-api:2.3
    junit:junit:4.12 --> jtidy:jtidy:4aug2000r7-dev
    junit:junit:4.12 --> javax.activation:activation:1.0.2
    junit:junit:4.12 --> javax.mail:mail:1.3.1
    junit:junit:4.12 --> org.hibernate:hibernate:3.2.6.ga
    junit:junit:4.12 --> org.hibernate:hibernate-annotations:3.3.1.GA
    junit:junit:4.12 --> org.hibernate:hibernate-commons-annotations:3.0.0.ga
    junit:junit:4.12 --> org.hibernate:ejb3-persistence:1.0.1.GA
    junit:junit:4.12 --> commons-logging:commons-logging:1.0.4
    junit:junit:4.12 --> javassist:javassist:3.4.GA
    junit:junit:4.12 --> org.hibernate:hibernate:3.2.6.ga
    junit:junit:4.12 --> org.hibernate:hibernate-commons-annotations:3.0.0.ga
    junit:junit:4.12 --> org.hibernate:ejb3-persistence:1.0.1.GA
    junit:junit:4.12 --> commons-logging:commons-logging:1.0.4
    junit:junit:4.12 --> commons-logging:commons-logging:1.0.4
    junit:junit:4.12 --> log4j:log4j:1.2.15
    junit:junit:4.12 --> commons-modeler:commons-modeler:2.0
    junit:junit:4.12 --> commons-collections:commons-collections:3.2.1
    junit:junit:4.12 --> commons-lang:commons-lang:2.4
    junit:junit:4.12 --> oro:oro:2.0.8
    junit:junit:4.12 --> jdom:jdom:1.0
    junit:junit:4.12 --> commons-logging:commons-logging:1.1
    junit:junit:4.12 --> log4j:log4j:1.2.12
    junit:junit:4.12 --> javax.servlet:servlet-api:2.3
    junit:junit:4.12 --> logkit:logkit:2.0
    junit:junit:4.12 --> ant:ant:1.6
    junit:junit:4.12 --> werken-xpath:werken-xpath:0.9.4
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> hsqldb:hsqldb:1.7.1
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> javax.inject:javax.inject:1
    junit:junit:4.12 --> aopalliance:aopalliance:1.0
    junit:junit:4.12 --> org.sonatype.sisu.inject:cglib:${cglib.version}
    junit:junit:4.12 --> javax.inject:javax.inject-tck:1
    junit:junit:4.12 --> org.springframework:spring-beans:3.0.5.RELEASE
    junit:junit:4.12 --> biz.aQute:bnd:0.0.384
    junit:junit:4.12 --> org.apache.felix:org.apache.felix.framework:3.0.5
    junit:junit:4.12 --> org.sonatype.sisu.inject:cglib:${cglib.version}
    junit:junit:4.12 --> ${pom.groupId}:javax.inject:1
    junit:junit:4.12 --> junit:junit:4.7
    junit:junit:4.12 --> javax.el:el-api:1.0
    junit:junit:4.12 --> javax.inject:javax.inject:1
    junit:junit:4.12 --> cglib:cglib-nodep:2.2
    junit:junit:4.12 --> org.springframework:spring-core:${project.version}
    junit:junit:4.12 --> log4j:log4j:unknown
    junit:junit:4.12 --> junit:junit:unknown
    junit:junit:4.12 --> org.easymock:easymock:unknown
    junit:junit:4.12 --> org.hamcrest:hamcrest-core:1.1
    junit:junit:4.12 --> ant:ant:1.6.5
    junit:junit:4.12 --> org.slf4j:slf4j-log4j12:1.0.1
    junit:junit:4.12 --> log4j:log4j:1.2.13
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> org.specs2:specs2-scalaz-core_2.9.2:6.0.1
    junit:junit:4.12 --> org.scala-lang:scala-compiler:2.9.2
    junit:junit:4.12 --> org.scalacheck:scalacheck_2.9.2:1.9
    junit:junit:4.12 --> org.scala-tools.testing:test-interface:0.5
    junit:junit:4.12 --> org.hamcrest:hamcrest-all:1.1
    junit:junit:4.12 --> org.mockito:mockito-all:1.9.0
    junit:junit:4.12 --> junit:junit:4.7
    junit:junit:4.12 --> org.pegdown:pegdown:1.0.2
    junit:junit:4.12 --> org.specs2:classycle:1.4.1
    junit:junit:4.12 --> org.scala-lang:scala-library:2.9.2
    junit:junit:4.12 --> org.scala-lang:scala-library:2.9.2
    junit:junit:4.12 --> org.scala-tools.testing:test-interface:0.5
    junit:junit:4.12 --> org.parboiled:parboiled-core:1.0.1
    junit:junit:4.12 --> org.parboiled:parboiled-java:1.0.1
    junit:junit:4.12 --> net.sf.jtidy:jtidy:r938
    junit:junit:4.12 --> org.testng:testng:5.14.10
    junit:junit:4.12 --> asm:asm-tree:3.3.1
    junit:junit:4.12 --> asm:asm-util:3.3.1
    junit:junit:4.12 --> asm:asm-analysis:3.3.1
    junit:junit:4.12 --> asm:asm:3.3.1
    junit:junit:4.12 --> org.parboiled:parboiled-core:1.0.1
    junit:junit:4.12 --> ant:ant:1.6.5
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> org.beanshell:bsh:2.0b4
    junit:junit:4.12 --> com.google.inject:guice:2.0
    junit:junit:4.12 --> com.beust:jcommander:1.5
    junit:junit:4.12 --> ant:ant:1.6.5
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> org.beanshell:bsh:2.0b4
    junit:junit:4.12 --> com.google.inject:guice:2.0
    junit:junit:4.12 --> com.beust:jcommander:1.12
    junit:junit:4.12 --> org.yaml:snakeyaml:1.6
    junit:junit:4.12 --> org.scala-lang:scala-library:2.9.1
    junit:junit:4.12 --> junit:junit:4.8.1
    junit:junit:4.12 --> org.apache.maven.surefire:maven-surefire-common:2.17
    junit:junit:4.12 --> org.apache.maven.surefire:common-junit48:2.17
    junit:junit:4.12 --> org.apache.maven.surefire:surefire-api:2.17
    junit:junit:4.12 --> org.apache.maven.surefire:surefire-shadefire:${shadedVersion}
    junit:junit:4.12 --> org.apache.maven:maven-plugin-api:2.0.9
    junit:junit:4.12 --> org.apache.maven.plugin-tools:maven-plugin-annotations:3.2
    junit:junit:4.12 --> org.apache.maven.surefire:surefire-api:2.17
    junit:junit:4.12 --> org.apache.maven.surefire:surefire-booter:2.17
    junit:junit:4.12 --> org.apache.maven:maven-artifact:2.0.9
    junit:junit:4.12 --> org.apache.maven:maven-plugin-descriptor:2.0.9
    junit:junit:4.12 --> org.apache.maven:maven-project:2.0.9
    junit:junit:4.12 --> org.apache.maven:maven-model:2.0.9
    junit:junit:4.12 --> org.apache.maven:maven-core:2.0.9
    junit:junit:4.12 --> org.apache.maven:maven-toolchain:2.0.9
    junit:junit:4.12 --> org.apache.commons:commons-lang3:3.1
    junit:junit:4.12 --> com.google.code.findbugs:jsr305:2.0.1
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> org.apache.maven:maven-artifact:3.0
    junit:junit:4.12 --> org.codehaus.plexus:plexus-utils:unknown
    junit:junit:4.12 --> org.apache.maven.surefire:surefire-shadefire:${shadedVersion}
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> org.apache.maven.surefire:surefire-api:unknown
    junit:junit:4.12 --> org.apache.maven.surefire:surefire-shadefire:${shadedVersion}
    junit:junit:4.12 --> org.codehaus.plexus:plexus-utils:unknown
    junit:junit:4.12 --> org.codehaus.plexus:plexus-container-default:unknown
    junit:junit:4.12 --> org.apache.maven:maven-plugin-api:unknown
    junit:junit:4.12 --> org.apache.maven:maven-artifact:unknown
    junit:junit:4.12 --> org.codehaus.plexus:plexus-container-default:unknown
    junit:junit:4.12 --> org.apache.maven:maven-settings:unknown
    junit:junit:4.12 --> org.apache.maven:maven-artifact-test:unknown
    junit:junit:4.12 --> org.apache.maven:maven-profile:unknown
    junit:junit:4.12 --> org.apache.maven:maven-model:unknown
    junit:junit:4.12 --> org.apache.maven:maven-artifact-manager:unknown
    junit:junit:4.12 --> org.apache.maven:maven-plugin-registry:unknown
    junit:junit:4.12 --> org.codehaus.plexus:plexus-utils:unknown
    junit:junit:4.12 --> org.apache.maven:maven-artifact:unknown
    junit:junit:4.12 --> org.codehaus.plexus:plexus-container-default:unknown
    junit:junit:4.12 --> org.codehaus.plexus:plexus-utils:unknown
    junit:junit:4.12 --> org.apache.maven:maven-settings:unknown
    junit:junit:4.12 --> org.apache.maven.wagon:wagon-file:unknown
    junit:junit:4.12 --> org.apache.maven:maven-plugin-parameter-documenter:unknown
    junit:junit:4.12 --> org.apache.maven.wagon:wagon-webdav:unknown
    junit:junit:4.12 --> org.apache.maven.wagon:wagon-http-lightweight:unknown
    junit:junit:4.12 --> org.apache.maven.reporting:maven-reporting-api:unknown
    junit:junit:4.12 --> org.apache.maven:maven-profile:unknown
    junit:junit:4.12 --> org.apache.maven:maven-model:unknown
    junit:junit:4.12 --> org.apache.maven:maven-artifact:unknown
    junit:junit:4.12 --> org.apache.maven.wagon:wagon-provider-api:unknown
    junit:junit:4.12 --> org.codehaus.plexus:plexus-container-default:unknown
    junit:junit:4.12 --> org.apache.maven:maven-repository-metadata:unknown
    junit:junit:4.12 --> org.apache.maven:maven-error-diagnostics:unknown
    junit:junit:4.12 --> org.apache.maven:maven-project:unknown
    junit:junit:4.12 --> commons-cli:commons-cli:1.0
    junit:junit:4.12 --> org.apache.maven:maven-plugin-api:unknown
    junit:junit:4.12 --> org.apache.maven.wagon:wagon-ssh-external:unknown
    junit:junit:4.12 --> org.apache.maven:maven-plugin-descriptor:unknown
    junit:junit:4.12 --> org.codehaus.plexus:plexus-interactivity-api:1.0-alpha-4
    junit:junit:4.12 --> org.apache.maven:maven-artifact-manager:unknown
    junit:junit:4.12 --> org.apache.maven:maven-monitor:unknown
    junit:junit:4.12 --> org.apache.maven.wagon:wagon-ssh:unknown
    junit:junit:4.12 --> org.codehaus.plexus:plexus-utils:unknown
    junit:junit:4.12 --> classworlds:classworlds:unknown
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> org.apache.maven:maven-core:2.0.9
    junit:junit:4.12 --> org.apache.maven:maven-artifact:2.0.9
    junit:junit:4.12 --> junit:junit:4.10
    junit:junit:4.12 --> commons-io:commons-io:2.1
    junit:junit:4.12 --> org.easymock:easymock:3.0
    junit:junit:4.12 --> junit:junit:4.10
    junit:junit:4.12 --> org.apache.maven.wagon:wagon-ssh:1.0
    junit:junit:4.12 --> com.jcraft:jsch:0.1.44-1
    junit:junit:4.12 --> org.codehaus.plexus:plexus-utils:unknown
    junit:junit:4.12 --> org.apache.maven.wagon:wagon-ssh-common:unknown
    junit:junit:4.12 --> org.apache.maven.wagon:wagon-ssh-common-test:unknown
    junit:junit:4.12 --> org.mortbay.jetty:jetty:6.1.11
    junit:junit:4.12 --> com.jcraft:jzlib:1.0.7
    junit:junit:4.12 --> junit:junit:3.8.1
    junit:junit:4.12 --> cglib:cglib-nodep:2.2
    junit:junit:4.12 --> org.objenesis:objenesis:1.2
    junit:junit:4.12 --> junit:junit:4.8.1
    junit:junit:4.12 --> org.apache.maven.surefire:common-junit4:${project.version}
    junit:junit:4.12 --> org.apache.maven.surefire:surefire-grouper:unknown
    junit:junit:4.12 --> org.apache.maven.shared:maven-shared-utils:unknown
    junit:junit:4.12 --> org.apache.maven.surefire:common-java5:${project.version}
